// ============================================================
// NÚCLEO essences — Catálogo de perfumes (marca y género).
//
// Se usa para completar automáticamente la marca y el género de
// cada aroma en el resumen del pedido (checkout) y en el correo
// interno de notificación (stripe-webhook.js).
//
// Las claves están en MAYÚSCULAS y sin acentos/comillas especiales
// normalizadas por normalizarAroma(), para que la búsqueda no
// falle por mayúsculas/minúsculas o tildes distintas.
// ============================================================

const CATALOGO_AROMAS = {
  '1 MILLION': { marca: 'PACO RABANNE', genero: 'Hombre' },
  '1 MILLION ELIXIR': { marca: 'PACO RABANNE', genero: 'Hombre' },
  '1 MILLION LUCKY': { marca: 'PACO RABANNE', genero: 'Hombre' },
  '1 MILLION PRIVE': { marca: 'PACO RABANNE', genero: 'Hombre' },
  '1 MILLION ROYAL': { marca: 'PACO RABANNE', genero: 'Hombre' },
  '1888': { marca: 'XERJOFF', genero: 'Unisex' },
  '212': { marca: 'CAROLINA HERRERA', genero: 'Mujer' },
  '212 HEROES': { marca: 'CAROLINA HERRERA', genero: 'Hombre' },
  '212 HEROES FOREVER YOUNG': { marca: 'CAROLINA HERRERA', genero: 'Mujer' },
  '212 MEN': { marca: 'CAROLINA HERRERA', genero: 'Hombre' },
  '212 SEXY': { marca: 'CAROLINA HERRERA', genero: 'Mujer' },
  '212 SEXY MEN': { marca: 'CAROLINA HERRERA', genero: 'Hombre' },
  '212 VIP': { marca: 'CAROLINA HERRERA', genero: 'Mujer' },
  '212 VIP BLACK': { marca: 'CAROLINA HERRERA', genero: 'Hombre' },
  '212 VIP MEN': { marca: 'CAROLINA HERRERA', genero: 'Hombre' },
  '212 VIP ROSE': { marca: 'CAROLINA HERRERA', genero: 'Mujer' },
  '212 VIP ROSE ELIXIR': { marca: 'CAROLINA HERRERA', genero: 'Mujer' },
  '360°': { marca: 'PERRY ELLIS', genero: 'Hombre' },
  '360° BLACK': { marca: 'PERRY ELLIS', genero: 'Hombre' },
  '360° DAMA': { marca: 'PERRY ELLIS', genero: 'Mujer' },
  '360° PINK': { marca: 'PERRY ELLIS', genero: 'Mujer' },
  '360° PURPLE': { marca: 'PERRY ELLIS', genero: 'Mujer' },
  '360° RED': { marca: 'PERRY ELLIS', genero: 'Hombre' },
  '5TA AVENUE': { marca: 'ELIZABETH ARDEN', genero: 'Mujer' },
  '724': { marca: 'MAISON FRANCIS KURKDJIAN', genero: 'Unisex' },
  '9 PM REBEL': { marca: 'AFNAN', genero: 'Hombre' },
  '9:00 PM': { marca: 'AFNAN', genero: 'Hombre' },
  'A*MEN': { marca: 'THIERRY MUGLER', genero: 'Hombre' },
  'ABSOLU AVENTUS': { marca: 'CREED', genero: 'Hombre' },
  'ACQUA DI GIO': { marca: 'GIORGIO ARMANI', genero: 'Mujer' },
  'ACQUA DI GIO POUR HOMME': { marca: 'GIORGIO ARMANI', genero: 'Hombre' },
  'ACQUA DI GIO PROFONDO': { marca: 'GIORGIO ARMANI', genero: 'Hombre' },
  'ACQUA DI GIO PROFUMO': { marca: 'GIORGIO ARMANI', genero: 'Hombre' },
  'ACQUA DI GIOIA': { marca: 'GIORGIO ARMANI', genero: 'Mujer' },
  'AFTERNOON SWIM': { marca: 'LOUIS VUITTON', genero: 'Unisex' },
  'AIRES DEL TIEMPO': { marca: 'NINA RICCI', genero: 'Mujer' },
  'ALEXANDRIA II': { marca: 'XERJOFF', genero: 'Unisex' },
  'ALIEN': { marca: 'THIERRY MUGLER', genero: 'Mujer' },
  'ALIEN GODDESS': { marca: 'THIERRY MUGLER', genero: 'Mujer' },
  'ALLURE HOMME EDITION BLANCHE': { marca: 'CHANEL', genero: 'Hombre' },
  'ALLURE HOMME SPORT EAU EXTREME': { marca: 'CHANEL', genero: 'Hombre' },
  'ALTHAIR': { marca: 'PARFUMS DE MARLY', genero: 'Hombre' },
  'AMARIGE': { marca: 'GIVENCHY', genero: 'Mujer' },
  'AMBER INTRIGUE': { marca: 'TOM FORD', genero: 'Unisex' },
  'AMBER OUD': { marca: 'AL HARAMAIN', genero: 'Unisex' },
  'AMBER OUD CARBON EDITION': { marca: 'AL HARAMAIN', genero: 'Unisex' },
  'AMBER OUD GOLD EDITION': { marca: 'AL HARAMAIN', genero: 'Unisex' },
  'AMBER OUD ROUGE': { marca: 'AL HARAMAIN', genero: 'Unisex' },
  'AMBERFUL': { marca: 'MANCERA', genero: 'Unisex' },
  'AMOR AMOR': { marca: 'CACHAREL', genero: 'Mujer' },
  'ANGE OU DEMON': { marca: 'GIVENCHY', genero: 'Mujer' },
  'ANGEL': { marca: 'THIERRY MUGLER', genero: 'Mujer' },
  'ANGEL EAU CROISSIERE': { marca: 'THIERRY MUGLER', genero: 'Mujer' },
  'ANGEL ICED STAR': { marca: 'THIERRY MUGLER', genero: 'Mujer' },
  'ANGEL NOVA': { marca: 'THIERRY MUGLER', genero: 'Mujer' },
  'ANGELS SHARE': { marca: 'BY KILIAN', genero: 'Unisex' },
  'ANIMALE': { marca: 'ANIMALE', genero: 'Mujer' },
  'ANIMALE FOR MEN': { marca: 'ANIMALE', genero: 'Hombre' },
  'ANOTHER 13': { marca: 'LE LABO', genero: 'Unisex' },
  'APRES LAMOUR': { marca: 'THOMAS KOSMALA', genero: 'Unisex' },
  'AQUA DI PARMA COLONIA': { marca: 'ACQUA DI PARMA', genero: 'Unisex' },
  'AQVA POUR HOMME': { marca: 'BVLGARI', genero: 'Hombre' },
  'ARI': { marca: 'ARIANA GRANDE', genero: 'Mujer' },
  'ARMANI CODE': { marca: 'GIORGIO ARMANI', genero: 'Hombre' },
  'ASAD': { marca: 'LATAFFA', genero: 'Hombre' },
  'ATOMIC ROSE': { marca: 'INITIO PARFUMS PRIVES', genero: 'Unisex' },
  'ATTRAPE REVES': { marca: 'LOUIS VUITTON', genero: 'Mujer' },
  'AVENTUS': { marca: 'CREED', genero: 'Hombre' },
  'AVENTUS COLOGNE': { marca: 'CREED', genero: 'Hombre' },
  'AVENTUS FOR HER': { marca: 'CREED', genero: 'Mujer' },
  'AZZARO': { marca: 'AZZARO', genero: 'Hombre' },
  'BACCARAT ROUGE 540': { marca: 'MAISON FRANCIS KURKDJIAN', genero: 'Unisex' },
  'BACCARAT ROUGE 540 EXTRAIT DE PARFUM': { marca: 'MAISON FRANCIS KURKDJIAN', genero: 'Unisex' },
  'BAD BOY': { marca: 'CAROLINA HERRERA', genero: 'Hombre' },
  'BAD BOY COBALT ELIXIR': { marca: 'CAROLINA HERRERA', genero: 'Hombre' },
  'BAD BOY COBALT PARFUM ELECTRIQUE': { marca: 'CAROLINA HERRERA', genero: 'Hombre' },
  'BAD BOY EXTREME': { marca: 'CAROLINA HERRERA', genero: 'Hombre' },
  'BAD BOY LE PARFUM': { marca: 'CAROLINA HERRERA', genero: 'Hombre' },
  'BAL DAFRIQUE': { marca: 'BYREDO', genero: 'Unisex' },
  'BARAONDA': { marca: 'NASOMATTO', genero: 'Unisex' },
  'BE DELICIOUS': { marca: 'DONNA KARAN', genero: 'Mujer' },
  'BECAUSE ITS YOU': { marca: 'GIORGIO ARMANI', genero: 'Mujer' },
  'BELLA VITA': { marca: 'GUESS', genero: 'Mujer' },
  'BERGAMOTE 22': { marca: 'LE LABO', genero: 'Unisex' },
  'BIANCO LATTE': { marca: 'GIARDINI DI TOSCANA', genero: 'Unisex' },
  'BIRDS OF PARADISE FOR MEN': { marca: 'CAROLINA HERRERA', genero: 'Hombre' },
  'BITTER PEACH': { marca: 'TOM FORD', genero: 'Unisex' },
  'BLACK OPIUM': { marca: 'YVES SAINT LAURENT', genero: 'Mujer' },
  'BLACK OPIUM ILLICIT GREEN': { marca: 'YVES SAINT LAURENT', genero: 'Mujer' },
  'BLACK ORQUID': { marca: 'TOM FORD', genero: 'Unisex' },
  'BLACK PHANTOM': { marca: 'BY KILIAN', genero: 'Hombre' },
  'BLEU': { marca: 'CHANEL', genero: 'Hombre' },
  'BLEU DE CHANEL LEXCLUSIF': { marca: 'CHANEL', genero: 'Hombre' },
  'BLOOM': { marca: 'GUCCI', genero: 'Mujer' },
  'BLUE LABEL': { marca: 'GIVENCHY', genero: 'Hombre' },
  'BLUE SEDUCTION': { marca: 'ANTONIO BANDERAS', genero: 'Hombre' },
  'BLUE TALISMAN': { marca: 'EX NIHILO', genero: 'Unisex' },
  'BOIS PACIFIQUE': { marca: 'TOM FORD', genero: 'Hombre' },
  'BOM DIA 40': { marca: 'SOL DE JANEIRO', genero: 'Mujer' },
  'BOMBSHELL': { marca: 'VICTORIA\'S SECRET', genero: 'Mujer' },
  'BON BON': { marca: 'VIKTOR&ROLF', genero: 'Mujer' },
  'BOND NO.9 PERFUME': { marca: 'BOND NO.9', genero: 'Unisex' },
  'BORN IN PARADISE': { marca: 'ESCADA', genero: 'Mujer' },
  'BORN IN ROMA THE GOLD DONNA': { marca: 'VALENTINO', genero: 'Mujer' },
  'BOSS BOTTLED': { marca: 'HUGO BOSS', genero: 'Hombre' },
  'BOSS BOTTLED ABSOLUTE': { marca: 'HUGO BOSS', genero: 'Hombre' },
  'BOSS BOTTLED ELIXIR': { marca: 'HUGO BOSS', genero: 'Hombre' },
  'BOSS BOTTLED INFINITE': { marca: 'HUGO BOSS', genero: 'Hombre' },
  'BOSS THE SCENT': { marca: 'HUGO BOSS', genero: 'Hombre' },
  'BOSS THE SCENT LE PARFUM': { marca: 'HUGO BOSS', genero: 'Hombre' },
  'BRIGHT CRYSTAL': { marca: 'VERSACE', genero: 'Mujer' },
  'BRIGHT CRYSTAL ABSOLU': { marca: 'VERSACE', genero: 'Mujer' },
  'BUM BUM 62': { marca: 'SOL DE JANEIRO', genero: 'Mujer' },
  'BURBERRY HER': { marca: 'BURBERRY', genero: 'Mujer' },
  'BURBERRY HER ELIXIR PARFUM': { marca: 'BURBERRY', genero: 'Mujer' },
  'BVLGARI MAN IN BLACK': { marca: 'BVLGARI', genero: 'Hombre' },
  'BY THE FIREPLACE': { marca: 'MAISON MARTIN MARGIELA', genero: 'Unisex' },
  'CAFE ROSE 2021': { marca: 'TOM FORD', genero: 'Unisex' },
  'CALIFORNIA DREAM': { marca: 'LOUIS VUITTON', genero: 'Mujer' },
  'CAN CAN': { marca: 'PARIS HILTON', genero: 'Mujer' },
  'CANDY': { marca: 'PRADA', genero: 'Mujer' },
  'CANT STOP LOVING YOU': { marca: 'BY KILIAN', genero: 'Mujer' },
  'CARAMEL ORQUID': { marca: 'KKW FRAGRANCE', genero: 'Mujer' },
  'CARLO CORINTO': { marca: 'CARLO CORINTO', genero: 'Hombre' },
  'CARMINA': { marca: 'CREED', genero: 'Mujer' },
  'CAROLINA HERRERA': { marca: 'CAROLINA HERRERA', genero: 'Mujer' },
  'CEDRAT BOISE': { marca: 'MANCERA', genero: 'Unisex' },
  'CELESTE': { marca: 'GIARDINI DI TOSCANA', genero: 'Unisex' },
  'CENTAURUS': { marca: 'CREED', genero: 'Unisex' },
  'CH': { marca: 'CAROLINA HERRERA', genero: 'Mujer' },
  'CH MEN': { marca: 'CAROLINA HERRERA', genero: 'Hombre' },
  'CH MEN PRIVE': { marca: 'CAROLINA HERRERA', genero: 'Hombre' },
  'CH MEN UNDER THE SEA': { marca: 'CAROLINA HERRERA', genero: 'Hombre' },
  'CH WOMAN UNDER THE SEA': { marca: 'CAROLINA HERRERA', genero: 'Mujer' },
  'CHAMPACA ABSOLUTE': { marca: 'TOM FORD', genero: 'Unisex' },
  'CHANCE': { marca: 'CHANEL', genero: 'Mujer' },
  'CHANCE EAU FRAICHE': { marca: 'CHANEL', genero: 'Mujer' },
  'CHANCE EAU SPLENDIDE': { marca: 'CHANEL', genero: 'Mujer' },
  'CHANCE EAU TENDRE': { marca: 'CHANEL', genero: 'Mujer' },
  'CHANEL NO.5': { marca: 'CHANEL', genero: 'Mujer' },
  'CHANGING CONSTANCY': { marca: 'PENHALIGON\'S', genero: 'Mujer' },
  'CHEAP & CHIC I LOVE LOVE': { marca: 'MOSCHINO', genero: 'Mujer' },
  'CHERRY SMOKE': { marca: 'TOM FORD', genero: 'Unisex' },
  'CHLOE EAU DE PARFUM': { marca: 'CHLOÉ', genero: 'Mujer' },
  'CHROME': { marca: 'AZZARO', genero: 'Hombre' },
  'CITY OF STARS': { marca: 'LOUIS VUITTON', genero: 'Unisex' },
  'CK ONE': { marca: 'CALVIN KLEIN', genero: 'Unisex' },
  'CK WOMAN': { marca: 'CALVIN KLEIN', genero: 'Mujer' },
  'CLOUD': { marca: 'ARIANA GRANDE', genero: 'Mujer' },
  'CLOUD INTENSE': { marca: 'ARIANA GRANDE', genero: 'Mujer' },
  'CLOUD PINK': { marca: 'ARIANA GRANDE', genero: 'Mujer' },
  'CLUB DE NUIT INTENSE': { marca: 'ARMAFF', genero: 'Mujer' },
  'CLUB DE NUIT INTENSE MAN': { marca: 'ARMAFF', genero: 'Hombre' },
  'CLUB DE NUIT SILLAGE': { marca: 'ARMAFF', genero: 'Unisex' },
  'COACH': { marca: 'COACH', genero: 'Mujer' },
  'COCO': { marca: 'CHANEL', genero: 'Mujer' },
  'COCO MADEMOISELLE': { marca: 'CHANEL', genero: 'Mujer' },
  'COCO MADEMOISELLE INTENSE': { marca: 'CHANEL', genero: 'Mujer' },
  'COSTA AZZURRA': { marca: 'TOM FORD', genero: 'Unisex' },
  'CRY BABY': { marca: 'MELANIE MARTINEZ', genero: 'Mujer' },
  'CRYSTAL NOIR': { marca: 'VERSACE', genero: 'Mujer' },
  'DAISY DREAM': { marca: 'MARC JACOBS', genero: 'Mujer' },
  'DAISY EVER SO FRESH': { marca: 'MARC JACOBS', genero: 'Mujer' },
  'DAISY SUNSHINE': { marca: 'MARC JACOBS', genero: 'Mujer' },
  'DECADENCE': { marca: 'MARC JACOBS', genero: 'Mujer' },
  'DECLARATION': { marca: 'CARTIER', genero: 'Hombre' },
  'DELICES': { marca: 'CARTIER', genero: 'Mujer' },
  'DELINA': { marca: 'PARFUMS DE MARLY', genero: 'Mujer' },
  'DELINA A LA ROSEE': { marca: 'PARFUMS DE MARLY', genero: 'Mujer' },
  'DELINA EXCLUSIF': { marca: 'PARFUMS DE MARLY', genero: 'Mujer' },
  'DELPHINUS': { marca: 'CREED', genero: 'Unisex' },
  'DEVOTION': { marca: 'DOLCE & GABBANA', genero: 'Mujer' },
  'DEVOTION POUR HOMME': { marca: 'DOLCE & GABBANA', genero: 'Hombre' },
  'DIOR ADDICT': { marca: 'DIOR', genero: 'Mujer' },
  'DIOR HOMME': { marca: 'DIOR', genero: 'Hombre' },
  'DIOR HOMME COLOGNE': { marca: 'DIOR', genero: 'Hombre' },
  'DIOR HOMME INTENSE': { marca: 'DIOR', genero: 'Hombre' },
  'DIOR HOMME SPORT': { marca: 'DIOR', genero: 'Hombre' },
  'DIORIVERA': { marca: 'DIOR (PRIVATE COLLECTION)', genero: 'Unisex' },
  'DOLCE & GABBANA': { marca: 'DOLCE & GABBANA', genero: 'Mujer' },
  'DOLCE & GABBANA POUR HOMME': { marca: 'DOLCE & GABBANA', genero: 'Hombre' },
  'DONNA BORN IN ROMA': { marca: 'VALENTINO', genero: 'Mujer' },
  'DONNA BORN IN ROMA INTENSE': { marca: 'VALENTINO', genero: 'Mujer' },
  'DONNA BORN IN ROMA YELLOW DREAM': { marca: 'VALENTINO', genero: 'Mujer' },
  'DRUNK LOVERS': { marca: 'BORNTOSTANDOUT', genero: 'Unisex' },
  'DYLAN BLUE': { marca: 'VERSACE', genero: 'Mujer' },
  'DYLAN BLUE FOR MEN': { marca: 'VERSACE', genero: 'Hombre' },
  'DYLAN PURPLE': { marca: 'VERSACE', genero: 'Mujer' },
  'DYLAN TURQUOISE': { marca: 'VERSACE', genero: 'Mujer' },
  'EARTH': { marca: 'LOEWE', genero: 'Unisex' },
  'EAU DE CARTIER': { marca: 'CARTIER', genero: 'Unisex' },
  'EAU FRAICHE': { marca: 'VERSACE', genero: 'Hombre' },
  'EBENE FUME': { marca: 'TOM FORD', genero: 'Unisex' },
  'EDEN JUICY APPLE': { marca: 'KAYALI FRAGRANCE', genero: 'Unisex' },
  'EDEN SPARKLYNG LYCHEE': { marca: 'KAYALI FRAGRANCE', genero: 'Mujer' },
  'EGOISTE PLATINUM': { marca: 'CHANEL', genero: 'Hombre' },
  'EILISH': { marca: 'BILLIE EILISH', genero: 'Mujer' },
  'ELADARIA': { marca: 'CREED', genero: 'Mujer' },
  'ELECTRIC CHERRY': { marca: 'TOM FORD', genero: 'Unisex' },
  'ELVES': { marca: 'LOUIS VUITTON', genero: 'Unisex' },
  'ELYSIUM POUR HOMME PARFUM': { marca: 'ROJA DOVE', genero: 'Hombre' },
  'EMBLEM': { marca: 'MONTBLANC', genero: 'Hombre' },
  'EMPORIO ARMANI LUI': { marca: 'GIORGIO ARMANI', genero: 'Hombre' },
  'ENGLISH PEAR & FREESIA': { marca: 'JO MALONE LONDON', genero: 'Unisex' },
  'ERBA PURA': { marca: 'XERJOFF', genero: 'Unisex' },
  'EROLFA': { marca: 'CREED', genero: 'Hombre' },
  'EROS EAU DE PARFUM': { marca: 'VERSACE', genero: 'Hombre' },
  'EROS ENERGY': { marca: 'VERSACE', genero: 'Hombre' },
  'EROS FLAME': { marca: 'VERSACE', genero: 'Hombre' },
  'EROS NAJIM': { marca: 'VERSACE', genero: 'Hombre' },
  'EROS POUR FEMME': { marca: 'VERSACE', genero: 'Mujer' },
  'ESSENCIA POUR HOMME': { marca: 'LOEWE', genero: 'Hombre' },
  'ETERNITY': { marca: 'CALVIN KLEIN', genero: 'Mujer' },
  'ETERNITY FOR MEN': { marca: 'CALVIN KLEIN', genero: 'Hombre' },
  'EUPHORIA': { marca: 'CALVIN KLEIN', genero: 'Mujer' },
  'EUPHORIA FOR MEN': { marca: 'CALVIN KLEIN', genero: 'Hombre' },
  'EXPLORER': { marca: 'MONTBLANC', genero: 'Hombre' },
  'EXPLORER EXTREME': { marca: 'MONTBLANC', genero: 'Hombre' },
  'FAME': { marca: 'PACO RABANNE', genero: 'Mujer' },
  'FAME LE PARFUM': { marca: 'PACO RABANNE', genero: 'Mujer' },
  'FANTASY': { marca: 'BRITNEY SPEARS', genero: 'Mujer' },
  'FARENHEIT': { marca: 'DIOR', genero: 'Hombre' },
  'FERRAGAMO': { marca: 'SALVATORE FERRAGAMO', genero: 'Hombre' },
  'FICO DI AMALFI': { marca: 'ACQUA DI PARMA', genero: 'Unisex' },
  'FIERCE': { marca: 'ABERCROMBIE & FITCH', genero: 'Hombre' },
  'FLEUR MUSC FOR HER': { marca: 'NARCISO RODRIGUEZ', genero: 'Mujer' },
  'FLORA BY GUCCI': { marca: 'GUCCI', genero: 'Mujer' },
  'FLORA GORGEOUS JAZMINE': { marca: 'GUCCI', genero: 'Mujer' },
  'FLORA GORGEOUS ORCHID': { marca: 'GUCCI', genero: 'Mujer' },
  'FLORABOTANICA': { marca: 'BALENCIAGA', genero: 'Mujer' },
  'FLOWER': { marca: 'KENZO', genero: 'Mujer' },
  'FLOWERBOMB': { marca: 'VIKTOR&ROLF', genero: 'Mujer' },
  'FRAGARIA': { marca: 'CREED', genero: 'Mujer' },
  'FUCKING FABULOUS': { marca: 'TOM FORD', genero: 'Unisex' },
  'GAULTIER DIVINE': { marca: 'JEAN PAUL GAULTIER', genero: 'Mujer' },
  'GENTLEMAN ONLY': { marca: 'GIVENCHY', genero: 'Hombre' },
  'GENTLEMAN SOCIETY': { marca: 'GIVENCHY', genero: 'Hombre' },
  'GINGER BISCUIT COLOGNE': { marca: 'JO MALONE LONDON', genero: 'Unisex' },
  'GOD IS A WOMAN': { marca: 'ARIANA GRANDE', genero: 'Mujer' },
  'GODDESS': { marca: 'BURBERRY', genero: 'Mujer' },
  'GOLD RUSH': { marca: 'PARIS HILTON', genero: 'Mujer' },
  'GOOD FORTUNE': { marca: 'VIKTOR&ROLF', genero: 'Mujer' },
  'GOOD GIRL': { marca: 'CAROLINA HERRERA', genero: 'Mujer' },
  'GOOD GIRL BLUSH': { marca: 'CAROLINA HERRERA', genero: 'Mujer' },
  'GRAND SOIR': { marca: 'MAISON FRANCIS KURKDJIAN', genero: 'Unisex' },
  'GREEN IRISH TWEED': { marca: 'CREED', genero: 'Hombre' },
  'GREENWICH VILLAGE': { marca: 'BOND NO.9', genero: 'Unisex' },
  'GRIS CHARNEL': { marca: 'BDK PARFUMS', genero: 'Unisex' },
  'GUCCI GUILTY BLACK POUR HOMME': { marca: 'GUCCI', genero: 'Hombre' },
  'GUCCI GUILTY POUR FEMME': { marca: 'GUCCI', genero: 'Mujer' },
  'GUCCI GUILTY POUR HOMME': { marca: 'GUCCI', genero: 'Hombre' },
  'GUIDANCE': { marca: 'AMOUAGE', genero: 'Mujer' },
  'GYPSY WATER': { marca: 'BYREDO', genero: 'Unisex' },
  'H24': { marca: 'HERMES', genero: 'Hombre' },
  'HABDAN': { marca: 'PARFUMS DE MARLY', genero: 'Unisex' },
  'HACIVAT': { marca: 'NISHANE', genero: 'Unisex' },
  'HALLOWEEN': { marca: 'JESUS DEL POZO', genero: 'Mujer' },
  'HALLOWEEN MAN': { marca: 'JESUS DEL POZO', genero: 'Hombre' },
  'HALLOWEEN MAN X': { marca: 'JESUS DEL POZO', genero: 'Hombre' },
  'HAPPY': { marca: 'CLINIQUE', genero: 'Mujer' },
  'HAYATTI': { marca: 'ATTAR COLLECTION', genero: 'Mujer' },
  'HEIRESS': { marca: 'PARIS HILTON', genero: 'Mujer' },
  'HERO PARFUM': { marca: 'BURBERRY', genero: 'Hombre' },
  'HEROD': { marca: 'PARFUMS DE MARLY', genero: 'Hombre' },
  'HERRERA FOR MEN': { marca: 'CAROLINA HERRERA', genero: 'Hombre' },
  'HIMALAYA': { marca: 'CREED', genero: 'Hombre' },
  'HUGO': { marca: 'HUGO BOSS', genero: 'Hombre' },
  'HYPNOSE': { marca: 'LANCOME', genero: 'Mujer' },
  'HYPNOTIC POISON': { marca: 'DIOR', genero: 'Mujer' },
  'I DONT NEED A PRINCE BY MY SIDE TO BE A PRINCESS': { marca: 'BY KILIAN', genero: 'Unisex' },
  'IDOLE': { marca: 'LANCOME', genero: 'Mujer' },
  'IMAGINATION': { marca: 'LOUIS VUITTON', genero: 'Hombre' },
  'IMPACT': { marca: 'TOMMY HILFINGER', genero: 'Hombre' },
  'INSTANT CRUSH': { marca: 'MANCERA', genero: 'Unisex' },
  'INVICTUS': { marca: 'PACO RABANNE', genero: 'Hombre' },
  'INVICTUS AQUA': { marca: 'PACO RABANNE', genero: 'Hombre' },
  'INVICTUS LEGEND': { marca: 'PACO RABANNE', genero: 'Hombre' },
  'INVICTUS PLATINUM': { marca: 'PACO RABANNE', genero: 'Hombre' },
  'INVICTUS VICTORY': { marca: 'PACO RABANNE', genero: 'Hombre' },
  'INVICTUS VICTORY ELIXIR': { marca: 'PACO RABANNE', genero: 'Hombre' },
  'IRRESISTIBLE EAU DE TOILETTE FRAICHE': { marca: 'GIVENCHY', genero: 'Mujer' },
  'JADORE': { marca: 'DIOR', genero: 'Mujer' },
  'JARDIN EXCLUSIF': { marca: 'MANCERA', genero: 'Unisex' },
  'JAZZ CLUB': { marca: 'MAISON MARTIN MARGIELA', genero: 'Hombre' },
  'JOY BY DIOR': { marca: 'DIOR', genero: 'Mujer' },
  'K BY D&G': { marca: 'DOLCE & GABBANA', genero: 'Hombre' },
  'KOS MUSE': { marca: 'KENIA OS', genero: 'Mujer' },
  'LA BELLE LE PARFUM': { marca: 'JEAN PAUL GAULTIER', genero: 'Mujer' },
  'LA BOMBA': { marca: 'CAROLINA HERRERA', genero: 'Mujer' },
  'LA NUIT DE LHOMME': { marca: 'YVES SAINT LAURENT', genero: 'Hombre' },
  'LA NUIT DE LHOMME BLUE ELECTRIQUE': { marca: 'YVES SAINT LAURENT', genero: 'Hombre' },
  'LA NUIT TRESOR': { marca: 'LANCOME', genero: 'Mujer' },
  'LA PETITE ROBE NOIR': { marca: 'GUERLAIN', genero: 'Mujer' },
  'LA VIE EST BELLE': { marca: 'LANCOME', genero: 'Mujer' },
  'LA VIE EST BELLE LECLAT': { marca: 'LANCOME', genero: 'Mujer' },
  'LA VIE EST BELLE LELIXIR': { marca: 'LANCOME', genero: 'Mujer' },
  'LADVENTURE': { marca: 'AL HARAMAIN', genero: 'Unisex' },
  'LADY MILLION': { marca: 'PACO RABANNE', genero: 'Mujer' },
  'LAFAYETTE STREET': { marca: 'BOND NO.9', genero: 'Unisex' },
  'LAVALLIERE': { marca: 'YVES SAINT LAURENT (PRIVATE COLLECTION)', genero: 'Unisex' },
  'LAVANDE 31': { marca: 'LE LABO', genero: 'Unisex' },
  'LAYTON': { marca: 'PARFUMS DE MARLY', genero: 'Unisex' },
  'LE BEAU': { marca: 'JEAN PAUL GAULTIER', genero: 'Hombre' },
  'LE BEAU LE PARFUM': { marca: 'JEAN PAUL GAULTIER', genero: 'Hombre' },
  'LE BEAU PARADISE GARDEN': { marca: 'JEAN PAUL GAULTIER', genero: 'Hombre' },
  'LE MALE': { marca: 'JEAN PAUL GAULTIER', genero: 'Hombre' },
  'LE MALE ELIXIR': { marca: 'JEAN PAUL GAULTIER', genero: 'Hombre' },
  'LE MALE LE PARFUM': { marca: 'JEAN PAUL GAULTIER', genero: 'Hombre' },
  'LEAU DISSEY POUR HOMME': { marca: 'ISSEY MIYAKE', genero: 'Hombre' },
  'LEAU DISSEY PURE NECTAR DE PARFUM': { marca: 'ISSEY MIYAKE', genero: 'Mujer' },
  'LEGACY OF PETRA': { marca: 'PENHALIGON\'S', genero: 'Mujer' },
  'LEGEND': { marca: 'MONTBLANC', genero: 'Hombre' },
  'LEGEND SPIRIT': { marca: 'MONTBLANC', genero: 'Hombre' },
  'LHOMME LIBRE': { marca: 'YVES SAINT LAURENT', genero: 'Hombre' },
  'LIBRE': { marca: 'YVES SAINT LAURENT', genero: 'Mujer' },
  'LIBRE INTENSE': { marca: 'YVES SAINT LAURENT', genero: 'Mujer' },
  'LIGHT BLUE': { marca: 'DOLCE & GABBANA', genero: 'Mujer' },
  'LIGHT BLUE FOREVER': { marca: 'DOLCE & GABBANA', genero: 'Hombre' },
  'LIGHT BLUE POUR HOMME': { marca: 'DOLCE & GABBANA', genero: 'Hombre' },
  'LIME BASIL & MANDARINE': { marca: 'JO MALONE LONDON', genero: 'Unisex' },
  'LIMMENSITE': { marca: 'LOUIS VUITTON', genero: 'Hombre' },
  'LIMPERATRICE 3': { marca: 'DOLCE & GABBANA', genero: 'Mujer' },
  'LINTERDIT EAU DE PARFUM': { marca: 'GIVENCHY', genero: 'Mujer' },
  'LIPSTICK ON': { marca: 'MAISON MARTIN MARGIELA', genero: 'Mujer' },
  'LOEWE 7': { marca: 'LOEWE', genero: 'Hombre' },
  'LOLITA LEMPICKA': { marca: 'LOLITA LEMPICKA', genero: 'Mujer' },
  'LOST CHERRY': { marca: 'TOM FORD', genero: 'Unisex' },
  'LOVE': { marca: 'SOFIA VERGARA', genero: 'Mujer' },
  'LOVE DONT BE SHY': { marca: 'BY KILIAN', genero: 'Mujer' },
  'LOVE IN WHITE': { marca: 'CREED', genero: 'Mujer' },
  'LOVEME': { marca: 'TOUS', genero: 'Mujer' },
  'LOVEME THE ONYS PARFUM': { marca: 'TOUS', genero: 'Mujer' },
  'LUNA ROSSA CARBON': { marca: 'PRADA', genero: 'Hombre' },
  'LUNA ROSSA OCEAN': { marca: 'PRADA', genero: 'Hombre' },
  'LYS 41': { marca: 'LE LABO', genero: 'Unisex' },
  'MALDIVES IN A BOTTLE YLANG COCO': { marca: 'KAYALI FRAGRANCES', genero: 'Mujer' },
  'MANDARINO DI AMALFI': { marca: 'TOM FORD', genero: 'Unisex' },
  'MARFA': { marca: 'MEMO PARIS', genero: 'Unisex' },
  'MEGAMARE': { marca: 'ORTO PARISI', genero: 'Unisex' },
  'MEOW': { marca: 'KATTY PERRY', genero: 'Mujer' },
  'METALLIQUE': { marca: 'TOM FORD', genero: 'Mujer' },
  'METEORE': { marca: 'LOUIS VUITTON', genero: 'Hombre' },
  'MILLESIME IMPERIAL': { marca: 'CREED', genero: 'Unisex' },
  'MILLION GOLD': { marca: 'PACO RABANNE', genero: 'Hombre' },
  'MIMOSA & CARDAMOM': { marca: 'JO MALONE LONDON', genero: 'Unisex' },
  'MIRACLE': { marca: 'LANCOME', genero: 'Mujer' },
  'MISS DIOR BLOOMING BOUQUET': { marca: 'DIOR', genero: 'Mujer' },
  'MISS DIOR EAU DE PARFUM': { marca: 'DIOR', genero: 'Mujer' },
  'MISS DIOR ESSENCE': { marca: 'DIOR', genero: 'Mujer' },
  'MISS DIOR ROSE NROSES': { marca: 'DIOR', genero: 'Mujer' },
  'MIU MIU FLEUR DE LAIT': { marca: 'MIU MIU', genero: 'Mujer' },
  'MOD BLUSH': { marca: 'ARIANA GRANDE', genero: 'Mujer' },
  'MOD VANILLA': { marca: 'ARIANA GRANDE', genero: 'Mujer' },
  'MOJAVE GHOST': { marca: 'BYREDO', genero: 'Unisex' },
  'MOLECULA 01': { marca: 'ESCENTRIC MOLECULES', genero: 'Unisex' },
  'MON GUERLAIN': { marca: 'GUERLAIN', genero: 'Mujer' },
  'MON PARIS': { marca: 'YVES SAINT LAURENT', genero: 'Mujer' },
  'MOONLIGHT': { marca: 'ARIANA GRANDE', genero: 'Mujer' },
  'MUSK THERAPY': { marca: 'INITIO PARFUMS PRIVES', genero: 'Unisex' },
  'MY WAY': { marca: 'GIORGIO ARMANI', genero: 'Mujer' },
  'MYRRH & TONKA': { marca: 'JO MALONE LONDON', genero: 'Unisex' },
  'MYSLF EAU DE PARFUM': { marca: 'YVES SAINT LAURENT', genero: 'Hombre' },
  'MYSLF LABSOLU': { marca: 'YVES SAINT LAURENT', genero: 'Hombre' },
  'NARCISO FOR HER': { marca: 'NARCISO RODRIGUEZ', genero: 'Mujer' },
  'NARCOTIC DELIGHT': { marca: 'INITIO PARFUMS PRIVES', genero: 'Unisex' },
  'NAUTICA VOYAGE': { marca: 'NAUTICA', genero: 'Hombre' },
  'NECTARINE BLOSSOM & HONEY': { marca: 'JO MALONE LONDON', genero: 'Unisex' },
  'NEROLI PORTOFINO': { marca: 'TOM FORD', genero: 'Unisex' },
  'NEW YORK OUD': { marca: 'BOND NO.9', genero: 'Unisex' },
  'NINA': { marca: 'NINA RICCI', genero: 'Mujer' },
  'NOIR EXTREME': { marca: 'TOM FORD', genero: 'Hombre' },
  'NOIR POUR FEMME': { marca: 'TOM FORD', genero: 'Mujer' },
  'OAJAN': { marca: 'PARFUMS DE MARLY', genero: 'Unisex' },
  'ODYSSEY CANDEE': { marca: 'ARMAF', genero: 'Mujer' },
  'OLYMPEA': { marca: 'PACO RABANNE', genero: 'Mujer' },
  'OMBRE LEATHER': { marca: 'TOM FORD', genero: 'Unisex' },
  'OMBRE NOMADE': { marca: 'LOUIS VUITTON', genero: 'Hombre' },
  'OMBRE ROSE LORIGINAL': { marca: 'JEAN CHARLES BROUSSEAU', genero: 'Mujer' },
  'OMNIA PARAIBA': { marca: 'BVLGARI', genero: 'Mujer' },
  'ONE & ONLY': { marca: 'GISSAH', genero: 'Mujer' },
  'ORIANA': { marca: 'PARFUMS DE MARLY', genero: 'Mujer' },
  'ORIGINAL SANTAL': { marca: 'CREED', genero: 'Unisex' },
  'OUD & BERGAMOTE': { marca: 'JO MALONE LONDON', genero: 'Unisex' },
  'OUD FOR GREATNESS': { marca: 'INITIO PARFUMS PRIVES', genero: 'Unisex' },
  'OUD FOR HAPPINESS': { marca: 'INITIO PARFUMS PRIVES', genero: 'Unisex' },
  'OUD MARACUJA': { marca: 'MAISON CRIVELI', genero: 'Unisex' },
  'OUD ROSEWOOD': { marca: 'DIOR (PRIVATE COLLECTION)', genero: 'Unisex' },
  'OUD SATIN MOOD': { marca: 'MAISON FRANCIS KURKDJIAN', genero: 'Unisex' },
  'OUD WOOD': { marca: 'TOM FORD', genero: 'Unisex' },
  'PACIFIC CHILL': { marca: 'LOUIS VUITTON', genero: 'Unisex' },
  'PARADIGME': { marca: 'PRADA', genero: 'Hombre' },
  'PARADOXE': { marca: 'PRADA', genero: 'Mujer' },
  'PARADOXE VIRTUAL FLOWER': { marca: 'PRADA', genero: 'Mujer' },
  'PARDON': { marca: 'NASOMATTO', genero: 'Hombre' },
  'PARIS HILTON': { marca: 'PARIS HILTON', genero: 'Mujer' },
  'PARIS HILTON FOR MEN': { marca: 'PARIS HILTON', genero: 'Hombre' },
  'PASHA': { marca: 'CARTIER', genero: 'Hombre' },
  'PEGASUS': { marca: 'PARFUMS DE MARLY', genero: 'Hombre' },
  'PERCIVAL': { marca: 'PARFUMS DE MARLY', genero: 'Unisex' },
  'PERFECT': { marca: 'MARC JACOBS', genero: 'Mujer' },
  'PERRY 18': { marca: 'PERRY ELLIS', genero: 'Hombre' },
  'PERSEUS': { marca: 'PARFUMS DE MARLY', genero: 'Hombre' },
  'PHANTOM': { marca: 'PACO RABANNE', genero: 'Hombre' },
  'PHANTOM LE PARFUM': { marca: 'PACO RABANNE', genero: 'Hombre' },
  'PHILOSYKOS EAU DE PARFUM': { marca: 'DYPTIQUE', genero: 'Unisex' },
  'PINK WOODS BY LOVENOTES': { marca: 'ARIANA GRANDE', genero: 'Mujer' },
  'PLEASURES': { marca: 'ESTEE LAUDER', genero: 'Mujer' },
  'POISON': { marca: 'DIOR', genero: 'Mujer' },
  'POISON GIRL': { marca: 'DIOR', genero: 'Mujer' },
  'POLO BLACK': { marca: 'RALPH LAUREN', genero: 'Hombre' },
  'POLO BLUE': { marca: 'RALPH LAUREN', genero: 'Hombre' },
  'POLO RED': { marca: 'RALPH LAUREN', genero: 'Hombre' },
  'POLO SPORT': { marca: 'RALPH LAUREN', genero: 'Hombre' },
  'POPPY & BARLEY': { marca: 'JO MALONE LONDON', genero: 'Unisex' },
  'POUR LUI FRENCH PANACHE': { marca: 'LACOSTE', genero: 'Hombre' },
  'PRADA AMBER POUR HOMME': { marca: 'PRADA', genero: 'Hombre' },
  'PRADA LHOMME': { marca: 'PRADA', genero: 'Hombre' },
  'PSYCHEDELIC LOVE': { marca: 'INITIO PARFUMS PRIVES', genero: 'Unisex' },
  'PURE XS FOR HER': { marca: 'PACO RABANNE', genero: 'Mujer' },
  'PURE XS FOR HIM': { marca: 'PACO RABANNE', genero: 'Hombre' },
  'Q BY D&G': { marca: 'DOLCE & GABBANA', genero: 'Mujer' },
  'QUEEN OF SILK': { marca: 'CREED', genero: 'Mujer' },
  'R.E.M': { marca: 'ARIANA GRANDE', genero: 'Mujer' },
  'R.E.M CHERRY ECLIPSE': { marca: 'ARIANA GRANDE', genero: 'Mujer' },
  'RALPH': { marca: 'RALPH LAUREN', genero: 'Mujer' },
  'RALPHS CLUB': { marca: 'RALPH LAUREN', genero: 'Hombre' },
  'RALPHS CLUB NEW YORK': { marca: 'RALPH LAUREN', genero: 'Hombre' },
  'RARE': { marca: 'RARE BEAUTY', genero: 'Mujer' },
  'RED TOBACCO': { marca: 'MANCERA', genero: 'Unisex' },
  'RIVERSIDE DRIVE': { marca: 'BOND NO.9', genero: 'Hombre' },
  'ROMANCE': { marca: 'RALPH LAUREN', genero: 'Mujer' },
  'ROSE 31': { marca: 'LE LABO', genero: 'Unisex' },
  'ROSE FOR HER': { marca: 'LACOSTE', genero: 'Mujer' },
  'ROSE PRICK': { marca: 'TOM FORD', genero: 'Unisex' },
  'ROSES VANILLE': { marca: 'MANCERA', genero: 'Unisex' },
  'ROYAL OUD': { marca: 'CREED', genero: 'Unisex' },
  'SANTAL 33': { marca: 'LE LABO', genero: 'Unisex' },
  'SANTAL BLUSH': { marca: 'TOM FORD', genero: 'Unisex' },
  'SAUVAGE EAU DE PARFUM': { marca: 'DIOR', genero: 'Hombre' },
  'SAUVAGE ELIXIR': { marca: 'DIOR', genero: 'Hombre' },
  'SCANDAL': { marca: 'JEAN PAUL GAULTIER', genero: 'Mujer' },
  'SCANDAL POUR HOMME': { marca: 'JEAN PAUL GAULTIER', genero: 'Hombre' },
  'SCANDAL POUR HOMME ABSOLU': { marca: 'JEAN PAUL GAULTIER', genero: 'Hombre' },
  'SCARLET POPPY COLOGNE INTENSE': { marca: 'JO MALONE LONDON', genero: 'Unisex' },
  'SELENA GOMEZ': { marca: 'SELENA GOMEZ', genero: 'Mujer' },
  'SI': { marca: 'GIORGIO ARMANI', genero: 'Mujer' },
  'SI PASSIONE': { marca: 'GIORGIO ARMANI', genero: 'Mujer' },
  'SIGNORINA': { marca: 'SALVATORE FERRAGAMO', genero: 'Mujer' },
  'SIGNORINA MISTERIOSA': { marca: 'SALVATORE FERRAGAMO', genero: 'Mujer' },
  'SILVER MOUNTAIN WATER': { marca: 'CREED', genero: 'Hombre' },
  'SMOKING HOT': { marca: 'BY KILIAN', genero: 'Unisex' },
  'SOLEIL BLANC': { marca: 'TOM FORD', genero: 'Unisex' },
  'SOLEIL DE FEU': { marca: 'TOM FORD', genero: 'Mujer' },
  'SOLO ELLA': { marca: 'LOEWE', genero: 'Mujer' },
  'SORBETTO ROSSO': { marca: 'ESCADA', genero: 'Mujer' },
  'SPEACHLESS': { marca: 'LORENZO PAZZAGLIA', genero: 'Unisex' },
  'SPELL ON YOU': { marca: 'LOUIS VUITTON', genero: 'Mujer' },
  'SPICE & WOOD': { marca: 'CREED', genero: 'Unisex' },
  'SPICEBOMB': { marca: 'VIKTOR&ROLF', genero: 'Hombre' },
  'SPICEBOMB INFRARED': { marca: 'VIKTOR&ROLF', genero: 'Hombre' },
  'SPICEBOMB METALLIC MUSK': { marca: 'VIKTOR&ROLF', genero: 'Hombre' },
  'STARWALKER': { marca: 'MONTBLANC', genero: 'Hombre' },
  'STELLA': { marca: 'STELLA McCARTNEY', genero: 'Mujer' },
  'STRONGER WITH YOU': { marca: 'GIORGIO ARMANI', genero: 'Hombre' },
  'STRONGER WITH YOU PARFUM': { marca: 'GIORGIO ARMANI', genero: 'Hombre' },
  'STRONGER WITH YOU SANDALWOOD': { marca: 'GIORGIO ARMANI', genero: 'Unisex' },
  'SUMMER HAMMER': { marca: 'LORENZO PAZZAGLIA', genero: 'Unisex' },
  'SUN SONG': { marca: 'LOUIS VUITTON', genero: 'Unisex' },
  'SWEET LIKE CANDY': { marca: 'ARIANA GRANDE', genero: 'Mujer' },
  'SWEET TOOTH': { marca: 'SABRINA CARPENTER', genero: 'Mujer' },
  'SWEET TOOTH LEMON PIE': { marca: 'SABRINA CARPENTER', genero: 'Mujer' },
  'SWISS ARMY': { marca: 'VICTORINOX SWISS ARMY', genero: 'Hombre' },
  'SYMPHONY': { marca: 'LOUIS VUITTON', genero: 'Unisex' },
  'TERRE DHERMES': { marca: 'HERMES', genero: 'Hombre' },
  'THANK U NEXT': { marca: 'ARIANA GRANDE', genero: 'Mujer' },
  'THANK U NEXT 2.0': { marca: 'ARIANA GRANDE', genero: 'Mujer' },
  'THE MATCHA 26': { marca: 'LE LABO', genero: 'Unisex' },
  'THE MOST WANTED': { marca: 'AZZARO', genero: 'Hombre' },
  'THE NOIR 29': { marca: 'LE LABO', genero: 'Unisex' },
  'THE ONE': { marca: 'DOLCE & GABBANA', genero: 'Mujer' },
  'THE ONE FOR MEN': { marca: 'DOLCE & GABBANA', genero: 'Hombre' },
  'THE ONE INTENSE': { marca: 'DOLCE & GABBANA', genero: 'Hombre' },
  'THE ONLY ONE': { marca: 'DOLCE & GABBANA', genero: 'Mujer' },
  'THE SCENT FOR HER': { marca: 'HUGO BOSS', genero: 'Mujer' },
  'THE WEDDING SILK SANTAL': { marca: 'KAYALI FRAGRANCE', genero: 'Unisex' },
  'TOBACCO & MANDARIN': { marca: 'JO MALONE LONDON', genero: 'Unisex' },
  'TOBACCO VANILLE': { marca: 'TOM FORD', genero: 'Unisex' },
  'TOMMY': { marca: 'TOMMY HILFINGER', genero: 'Hombre' },
  'TOMMY GIRL': { marca: 'TOMMY HILFINGER', genero: 'Mujer' },
  'TORINO 21': { marca: 'XERJOFF', genero: 'Unisex' },
  'TORINO 22': { marca: 'XERJOFF', genero: 'Unisex' },
  'TOUCH OF PINK': { marca: 'LACOSTE', genero: 'Mujer' },
  'TOY 2': { marca: 'MOSCHINO', genero: 'Mujer' },
  'TOY 2 BUBBLE GUM': { marca: 'MOSCHINO', genero: 'Mujer' },
  'TOY BOY': { marca: 'MOSCHINO', genero: 'Hombre' },
  'TRIBECA': { marca: 'BOND NO.9', genero: 'Unisex' },
  'TUSCAN LEATHER': { marca: 'TOM FORD', genero: 'Unisex' },
  'TUTTI TWILLY': { marca: 'HERMES', genero: 'Mujer' },
  'TUXEDO': { marca: 'YVES SAINT LAURENT (PRIVATE COLLECTION)', genero: 'Unisex' },
  'TWILLY': { marca: 'HERMES', genero: 'Mujer' },
  'TYGAR': { marca: 'BVLGARI', genero: 'Hombre' },
  'ULTRAMALE': { marca: 'JEAN PAUL GAULTIER', genero: 'Hombre' },
  'UOMO BORN IN ROMA': { marca: 'VALENTINO', genero: 'Hombre' },
  'UOMO BORN IN ROMA CORAL FANTASY': { marca: 'VALENTINO', genero: 'Hombre' },
  'UOMO BORN IN ROMA GREEN STRAVAGANZA': { marca: 'VALENTINO', genero: 'Hombre' },
  'UOMO BORN IN ROMA INTENSE': { marca: 'VALENTINO', genero: 'Hombre' },
  'UOMO BORN IN ROMA IVORY': { marca: 'VALENTINO', genero: 'Hombre' },
  'UOMO BORN IN ROMA ROCKSTUD NOIR': { marca: 'VALENTINO', genero: 'Hombre' },
  'UOMO BORN IN ROMA YELLOW DREAM': { marca: 'VALENTINO', genero: 'Hombre' },
  'UOMO SALVATORE': { marca: 'SALVATORE FERRAGAMO', genero: 'Hombre' },
  'VALAYA': { marca: 'PARFUMS DE MARLY', genero: 'Mujer' },
  'VALENTINA': { marca: 'VALENTINO', genero: 'Mujer' },
  'VALENTINA PINK': { marca: 'VALENTINO', genero: 'Mujer' },
  'VALENTINO DONNA BORN IN ROMA IVORY': { marca: 'VALENTINO', genero: 'Mujer' },
  'VALENTINO DONNA BORN IN ROMA PURPLE MELANCHOLIA': { marca: 'VALENTINO', genero: 'Mujer' },
  'VALENTINO UOMO': { marca: 'VALENTINO', genero: 'Hombre' },
  'VALENTINO UOMO BORN IN ROMA PURPLE MELANCHOLIA': { marca: 'VALENTINO', genero: 'Hombre' },
  'VANILLA 28': { marca: 'KAYALI FRAGRANCE', genero: 'Unisex' },
  'VANILLA 44 PARIS': { marca: 'LE LABO', genero: 'Unisex' },
  'VANILLA CANDY ROCK SUGAR': { marca: 'KAYALI FRAGRANCE', genero: 'Mujer' },
  'VANILLA LACE': { marca: 'VICTORIA\'S SECRET', genero: 'Mujer' },
  'VELVET INFUSION': { marca: 'D&G (PRIVATE COLLECTION)', genero: 'Unisex' },
  'VERSACE POUR HOMME': { marca: 'VERSACE', genero: 'Hombre' },
  'VERSENCE': { marca: 'VERSACE', genero: 'Mujer' },
  'VERY GOOD GIRL': { marca: 'CAROLINA HERRERA', genero: 'Mujer' },
  'VERY GOOD GIRL ELIXIR': { marca: 'CAROLINA HERRERA', genero: 'Mujer' },
  'VERY IRRESISTIBLE': { marca: 'GIVENCHY', genero: 'Mujer' },
  'VIKING COLOGNE': { marca: 'CREED', genero: 'Hombre' },
  'VIRGIN ISLAND WATER': { marca: 'CREED', genero: 'Unisex' },
  'VIVA LA JUICY': { marca: 'JUICY COUTURE', genero: 'Mujer' },
  'VOCE VIVA': { marca: 'VALENTINO', genero: 'Mujer' },
  'VODKA ON THE ROCKS': { marca: 'BY KILIAN', genero: 'Hombre' },
  'WALL STREET': { marca: 'BOND NO.9', genero: 'Unisex' },
  'WANTED BY NIGHT': { marca: 'AZZARO', genero: 'Hombre' },
  'WAVECHILD': { marca: 'ROOM1015', genero: 'Unisex' },
  'WHITE': { marca: 'LACOSTE', genero: 'Hombre' },
  'WICKED FOR GOOD - GLINDA BUBBLY PINK': { marca: 'ARIANA GRANDE', genero: 'Unisex' },
  'WILD VETIVER': { marca: 'CREED', genero: 'Unisex' },
  'WIND FLOWERS': { marca: 'CREED', genero: 'Mujer' },
  'WOMAN': { marca: 'RALPH LAUREN', genero: 'Mujer' },
  'WOOD SAGE & SEA SALT': { marca: 'JO MALONE LONDON', genero: 'Unisex' },
  'XJ 1861 NAXOS': { marca: 'XERJOFF', genero: 'Unisex' },
  'Y EAU DE PARFUM': { marca: 'YVES SAINT LAURENT', genero: 'Hombre' },
  'Y EAU DE PARFUM INTENSE': { marca: 'YVES SAINT LAURENT', genero: 'Hombre' },
  'Y ELIXIR': { marca: 'YVES SAINT LAURENT', genero: 'Hombre' },
  'Y ICED COLOGNE': { marca: 'YVES SAINT LAURENT', genero: 'Hombre' },
  'YARA': { marca: 'LATAFFA', genero: 'Mujer' },
  'YELLOW DIAMOND': { marca: 'VERSACE', genero: 'Mujer' },
  'YES I AM': { marca: 'CACHAREL', genero: 'Mujer' },
  'YUM BOUJEE MARSHMALLOW': { marca: 'KAYALI FRAGRANCE', genero: 'Unisex' },
  'YUM PISTACHO GELATO': { marca: 'KAYALI FRAGRANCE', genero: 'Unisex' },
  'Z ZEGNA': { marca: 'ERMENEGILDO ZEGNA', genero: 'Hombre' },
};

// Normaliza un texto de aroma (quita tildes, comillas, espacios extra)
// para buscarlo en CATALOGO_AROMAS sin importar cómo lo haya escrito
// el cliente o cómo esté guardado el nombre del producto.
function normalizarAroma(texto) {
  return String(texto || '')
    .toUpperCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[’´']/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

// Busca la marca y el género de un aroma por su nombre.
// Devuelve { marca, genero } o null si no está en el catálogo
// (por ejemplo, si el cliente escribió un aroma no listado).
function buscarAroma(nombreAroma) {
  const key = normalizarAroma(nombreAroma);
  return CATALOGO_AROMAS[key] || null;
}

module.exports = { CATALOGO_AROMAS, normalizarAroma, buscarAroma };
